services:
  postgres_db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dronejobs
